### ISSUE TITLE
ImportError: No module named 'params_flow'

### ISSUE THREAD

**Issue by adelgiudice** [kpe/bert-for-tf2#11]
looks like in issue with pip install and a missing module?

```Complete output (9 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-p1fqbaa5/bert-for-tf2/setup.py", line 10, in <module>
        import bert
      File "/tmp/pip-install-p1fqbaa5/bert-for-tf2/bert/__init__.py", line 7, in <module>
        from .layer import Layer
      File "/tmp/pip-install-p1fqbaa5/bert-for-tf2/bert/layer.py", line 10, in <module>
        import params_flow
    ImportError: No module named 'params_flow'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.```

**Comment by adelgiudice** [comment]
And after I manually install perams-flow I get: 
```  Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-1vh290id/bert-for-tf2/setup.py", line 16, in <module>
        with open("requirements.txt", "r") as reader:
    FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by adelgiudice** [comment]
I was attempting to install on Pv 3.5.2 but I was in another virtual environment.  When i build a fresh venv and try to install, there was no problem.  I'll investigate further and if I find something I'll let you know. Sorry for the false alarm, and thanks for your prompt reply.
