### ISSUE TITLE
Problems loading the readme

### ISSUE THREAD

**Issue by ralphbrooks** [kpe/bert-for-tf2#2]
I am attempting to get a pre-trained BERT layer working in TF 2.0. Said differently, I don't have the computing resources to train BERT myself, and as a result I am looking to use pre-trained weights so that I can do an advanced sentiment analysis in English. 

When I run the README python (below), I keep getting list index out of range errors. I am not sure if the ckpt file is correct or if I am not pulling the the weights from the correct location. Thoughts?

```
wget https://storage.googleapis.com/bert_models/2018_11_03/multilingual_L-12_H-768_A-12.zip
unzip multilingual_L-12_H-768_A-12.zip


ralph_a_brooks@main-keras-p4-instance:~$ pwd
/home/ralph_a_brooks
ralph_a_brooks@main-keras-p4-instance:~$ cd multilingual_L-12_H-768_A-12
ralph_a_brooks@main-keras-p4-instance:~/multilingual_L-12_H-768_A-12$ ls
bert_config.json  bert_model.ckpt.data-00000-of-00001  bert_model.ckpt.index  bert_model.ckpt.meta  vocab.txt
```

```
ralph_a_brooks@main-keras-p4-instance:~/multilingual_L-12_H-768_A-12$ python
Python 3.7.0 (default, Oct  9 2018, 10:31:47) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import os
>>> import tensorflow as tf
>>> from tensorflow.python import keras
>>> from bert import BertModelLayer
>>> from bert.loader import StockBertConfig, load_stock_weights
>>> 
>>> print(os.environ['HOME_PATH'])
/home/ralph_a_brooks
>>> 
>>> model_dir = os.environ['HOME_PATH']+"/multilingual_L-12_H-768_A-12"
>>> print(model_dir)
/home/ralph_a_brooks/multilingual_L-12_H-768_A-12
>>> 
>>> bert_config_file = os.path.join(model_dir, "bert_config.json")
>>> bert_ckpt_file   = os.path.join(model_dir, "bert_model.ckpt")
>>> 
>>> with tf.io.gfile.GFile(bert_config_file, "r") as reader:
...   stock_params = StockBertConfig.from_json_string(reader.read())
...   bert_params  = stock_params.to_bert_model_layer_params()
... 
>>> l_bert = BertModelLayer.from_params(bert_params, name="bert")
>>> load_stock_weights(l_bert, bert_ckpt_file)
WARNING: Logging before flag parsing goes to stderr.
W0605 17:39:47.570813 139787705705856 deprecation.py:323] From /home/ralph_a_brooks/.local/lib/python3.7/site-packages/bert/loader.py:113: checkpoint_exists (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.
Instructions for updating:
Use standard file APIs to check for files with this prefix.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ralph_a_brooks/.local/lib/python3.7/site-packages/bert/loader.py", line 116, in load_stock_weights
    bert_prefix = bert.weights[0].name.split("/")[0]
IndexError: list index out of range
```

**Comment by kpe** [comment]
@ralphbrooks - thank you for the message. I think the example in the README was somewhat short. The model variables in Keras seems to be created, only after the model has been build, i.e. keras needs to know some of the dimensions of the input to properly calculate the dimensions of the weights. So a more complete example might look like this (note the call to `Model.build`):
``` python
        print(model_dir)

        bert_config_file = os.path.join(model_dir, "bert_config.json")
        bert_ckpt_file   = os.path.join(model_dir, "bert_model.ckpt")

        with tf.io.gfile.GFile(bert_config_file, "r") as reader:
            stock_params = StockBertConfig.from_json_string(reader.read())
            bert_params  = stock_params.to_bert_model_layer_params()

        l_bert = BertModelLayer.from_params(bert_params, name="bert")

        max_seq_len=128
        l_input_ids      = keras.layers.Input(shape=(max_seq_len,), dtype='int32', name="input_ids")
        l_token_type_ids = keras.layers.Input(shape=(max_seq_len,), dtype='int32', name="token_type_ids")
        output = l_bert([l_input_ids, l_token_type_ids])

        model = keras.Model(inputs=[l_input_ids, l_token_type_ids], outputs=output)
        model.build(input_shape=[(None, max_seq_len),
                                 (None, max_seq_len)])

        load_stock_weights(l_bert, bert_ckpt_file)

```

**N.B** you might also find some of the unitests under `tests` useful.

**Comment by kpe** [comment]
an example on sentiment classifier fine-tuning could now be found under `examples/`.
