### ISSUE TITLE
installation error: Unicode Error

### ISSUE THREAD

**Issue by albertnanda** [kpe/bert-for-tf2#35]
`Looking in indexes: https://pypi.org/simple, https://pip:****@pip.ml.moodysanalytics.com/simple
Collecting bert-for-tf2
  Using cached https://files.pythonhosted.org/packages/93/31/1f9d1d5ccafb5b8bb621b02c4c5bd9e9f6599ec9b305f7307f1b6c5ae0b5/bert-for-tf2-0.12.7.tar.gz
    ERROR: Command errored out with exit status 1:
     command: /workspaces/albert/anaconda3/envs/tf_gpu/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-mzla9yhq/bert-for-tf2/setup.py'"'"'; __file__='"'"'/tmp/pip-install-mzla9yhq/bert-for-tf2/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-mzla9yhq/bert-for-tf2/pip-egg-info
         cwd: /tmp/pip-install-mzla9yhq/bert-for-tf2/
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-mzla9yhq/bert-for-tf2/setup.py", line 21, in <module>
        long_description = fh.read()
      File "/workspaces/albert/anaconda3/envs/tf_gpu/lib/python3.6/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xe4 in position 8479: ordinal not in range(128)
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.`

Environment:
Python: 3.6.9
OS: CentOS

**Comment by albertnanda** [comment]
Solution: export LANG=en_US.UTF-8
